urls.py
from django.conf.urls import url
from otree.default_urls import urlpatterns
from trust import focus
# from . import views
print('SUKA')
urlpatterns.append(url(r'^trust/export/$', focus.focustable))

real_effort/models.py
from otree.api import (
    models, widgets, BaseConstants, BaseSubsession, BaseGroup, BasePlayer,
    Currency as c, currency_range
)
import random

doc = """
This is a task that requires real effort from participants.
Subjects are shown two images of incomprehensible text.
Subjects are required to transcribe (copy) the text into a text entry field.
The quality of a subject's transcription is measured by the
<a href="http://en.wikipedia.org/wiki/Levenshtein_distance">Levenshtein distance</a>.
"""


def levenshtein(a, b):
    """Calculates the Levenshtein distance between a and b."""
    n, m = len(a), len(b)
    if n > m:
        # Make sure n <= m, to use O(min(n,m)) space
        a, b = b, a
        n, m = m, n

    current = range(n + 1)
    for i in range(1, m + 1):
        previous, current = current, [i] + [0] * n
        for j in range(1, n + 1):
            add, delete = previous[j] + 1, current[j - 1] + 1
            change = previous[j - 1]
            if a[j - 1] != b[i - 1]:
                change = change + 1
            current[j] = min(add, delete, change)

    return current[n]


def distance_and_ok(transcribed_text, reference_text, max_error_rate):
    error_threshold = len(reference_text) * max_error_rate
    distance = levenshtein(transcribed_text, reference_text)
    ok = distance <= error_threshold
    return distance, ok


class Constants(BaseConstants):
    name_in_url = 'real_effort'
    players_per_group = None
    num_rounds = 2

    reference_texts = [
        "Revealed preference",
        "Hex ton satoha egavecen. Loh ta receso minenes da linoyiy xese coreliet ocotine! Senuh asud tu bubo tixorut sola, bo ipacape le rorisin lesiku etutale saseriec niyacin ponim na. Ri arariye senayi esoced behin? Tefid oveve duk mosar rototo buc: Leseri binin nolelar sise etolegus ibosa farare. Desac eno titeda res vab no mes!",
    ]

    allowed_error_rates = [0, 0.03]


class Subsession(BaseSubsession):
    pass


class Group(BaseGroup):
    pass


class Player(BasePlayer):
    transcribed_text = models.TextField()
    levenshtein_distance = models.PositiveIntegerField()

real_effort/views.py
from . import models
from ._builtin import Page, WaitPage
from otree.api import Currency as c, currency_range
from .models import Constants, levenshtein, distance_and_ok
from django.conf import settings


class Transcribe(Page):
    form_model = models.Player
    form_fields = ['transcribed_text']

    def vars_for_template(self):

        return {
            'image_path': 'real_effort/paragraphs/{}.png'.format(
                self.round_number),
            'reference_text': Constants.reference_texts[self.round_number - 1],
            'debug': settings.DEBUG,
            'required_accuracy': 100 * (1 - Constants.allowed_error_rates[self.round_number - 1])
        }

    def transcribed_text_error_message(self, transcribed_text):
        reference_text = Constants.reference_texts[self.round_number - 1]
        allowed_error_rate = Constants.allowed_error_rates[
            self.round_number - 1]
        distance, ok = distance_and_ok(transcribed_text, reference_text,
                                       allowed_error_rate)
        if ok:
            self.player.levenshtein_distance = distance
        else:
            if allowed_error_rate == 0:
                return "The transcription should be exactly the same as on the image."
            else:
                return "This transcription appears to contain too many errors."

    def before_next_page(self):
        self.player.payoff = 0


class Results(Page):
    def is_displayed(self):
        return self.round_number == Constants.num_rounds

    def vars_for_template(self):
        table_rows = []
        for prev_player in self.player.in_all_rounds():
            row = {
                'round_number': prev_player.round_number,
                'reference_text_length': len(Constants.reference_texts[prev_player.round_number - 1]),
                'transcribed_text_length': len(prev_player.transcribed_text),
                'distance': prev_player.levenshtein_distance,
            }
            table_rows.append(row)

        return {'table_rows': table_rows}


page_sequence = [Transcribe, Results]

real_effort/templates/real_effort/Results.html
{% extends "global/Base.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    Summary
{% endblock %}

{% block content %}

    <p class="text-success">
        The table below shows some statistics for the transcriptions you have entered. 
        In a real study this table would usually not be shown to subjects.
        <br>
        The <a href="http://en.wikipedia.org/wiki/Levenshtein_distance">Levenshtein</a> distance is given in the last column.
        Note that the difference between the length of the given text and the length of
        the text entered is a lower bound on the Levenshtein distance.
    </p>

    <div class="panel panel-success">

        <div class="panel-heading">
                Statistics for transcriptions
        </div>

        <table class="table">
            <tr>
                <th>Transcription #</th>
                <th>Length of given text</th>
                <th>Length of text entered</th>
                <th>Levenshtein distance</th>
            </tr>
            {% for row in table_rows %}
            <tr>
                <td>{{ row.round_number }}</td>
                <td>{{ row.reference_text_length }}</td>
                <td>{{ row.transcribed_text_length }}</td>
                <td>{{ row.distance }}</td>
            </tr>
            {% endfor %}

        </table>

    </div>

{% endblock %}

real_effort/templates/real_effort/Transcribe.html
{% extends "global/Base.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    Transcription task {{ subsession.round_number }}/{{ Constants.num_rounds }}
{% endblock %}

{% block content %}

    <p>
        Please transcribe (copy) the text below into the input field.
        Be exact and make sure to get all characters and spaces correct.
    </p>

    <div>
        <img src="{% static image_path %}"/>
    </div>

    {% formfield player.transcribed_text with label="" %}

    {% next_button %}

    {% if debug %}
        <div class="box papereffect">
            <h4>Explanation for researchers (shown in debug mode only)</h4>
            <p>
                You are playing in debug mode, so you can skip the manual
                transcription
                by clicking <a href="#" id="prefill">this link</a>
                and clicking "next".
            </p>

            <p>
                A subject can only advance to the next screen if the
                transcription is {{ required_accuracy }}% accurate.
            </p>
        </div>
        <script>
            $(document).ready(function () {
                $('a#prefill').click(function () {
                    $('#id_transcribed_text').val('{{ reference_text }}');
                })
            });
        </script>

    {% endif %}
{% endblock %}